### ISSUE TITLE
R5S openclash连接超时

### ISSUE THREAD

**Issue by raydoomed** [DHDAXCW/NanoPi-R5S-R5C#17]
openclash好像也有问题，是不是和passwall一样对UDP要求很高？一直连接超时无法上网

**Comment by raydoomed** [comment]
docker版

**Comment by raydoomed** [comment]
目前测试下来，openclash国内无法上网，国外正常上网，docker版。不知道什么原因

**Comment by raydoomed** [comment]
补充：当无法上国内网后，关闭openclash后也上不去网，全网断~！全插件版就没问题，估计和docker有关？

**Comment by DHDAXCW** [comment]
把udp关了

**Comment by raydoomed** [comment]
> 把udp关了

udp关了我dns怎么办?通过其他上游dns?

**Comment by raydoomed** [comment]
> 把udp关了还是这样咯

![Screenshot_2023-01-15-14-43-43-114_com.microsoft.emmx.jpg](https://user-images.githubusercontent.com/57515812/212526896-bd576e78-6e31-4df4-ab1e-3d61460f715e.jpg)
![Screenshot_2023-01-15-14-43-55-063_com.microsoft.emmx.jpg](https://user-images.githubusercontent.com/57515812/212526909-03813717-614f-4881-b1c8-d3adbdfa53b3.jpg)

**Comment by raydoomed** [comment]
选了fake-ip增强模式  tun模式  host tun模式  什么模式都选了一遍  偶尔能访问，能访问芒果TV但不能访问百度，如果有具体参数设置麻烦请告知

**Comment by raydoomed** [comment]
找到问题所在了   在全局模式下 把绕过中国大陆IP关闭就好了
