### ISSUE TITLE
固件如何升级？

### ISSUE THREAD

**Issue by raydoomed** [DHDAXCW/NanoPi-R5S-R5C#20]
使用web里的刷写新固件后还是旧版本。。解压用sysupgrade命令又提示/tmp空间不足。。

**Comment by DHDAXCW** [comment]
线刷线刷

**Comment by raydoomed** [comment]
> 线刷线刷线刷好烦的🌝🌝

**Comment by raydoomed** [comment]
> 线刷线刷

线刷我配置是不是就没了?🌚🌚

**Comment by DHDAXCW** [comment]
那你爱刷不刷？

**Comment by raydoomed** [comment]
哈哈哈哈，先不刷，暂时用的1月16日版本，还没什么大问题。这东西每天一更每天重刷吃不消啊哥，想办法能通过web直接升级就好了。我天天更

**Comment by raydoomed** [comment]
把/tmp挂载改成3-4G，R5S有16G硬盘呢，这样应该就可以通过web来升级了，要么哥你整个小点的升级包也行

**Comment by DHDAXCW** [comment]
![image](https://user-images.githubusercontent.com/74764072/213210097-422ab61f-9cd8-4586-9da6-6359340ffae4.jpeg)

**Comment by raydoomed** [comment]
> ![image](https://user-images.githubusercontent.com/74764072/213210097-422ab61f-9cd8-4586-9da6-6359340ffae4.jpeg)

哈哈哈哈哈哈哈，夜宵吃完有力气干活了
