### ISSUE TITLE
哥，我又来了，哈哈哈，zsh问题

### ISSUE THREAD

**Issue by raydoomed** [DHDAXCW/NanoPi-R5S-R5C#21]
新年快乐啊哥哈哈哈
言归正传
ext4版本 ssh登录出现zsh没有此目录
![mmexport1674212388466.png](https://user-images.githubusercontent.com/57515812/213680193-a3cda04c-c247-4b42-b9d9-7b8decc78e7c.png)

**Comment by DHDAXCW** [comment]
已知问题，正在排查

**Comment by DHDAXCW** [comment]
已修复，等今天版本
