### ISSUE TITLE
R5C

### ISSUE THREAD

**Issue by bg7pge** [DHDAXCW/NanoPi-R5S-R5C#22]
刷好了R5C的固件，但是无法显示无线功能，不知道为什么？？？

**Comment by DHDAXCW** [comment]
不带无线，后面考虑加个。我现在没有这个机器

**Comment by bg7pge** [comment]
好的，多谢了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年01月24日 09:05 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [DHDAXCW/NanoPi-R5S-R5C] R5C (Issue #22) |

不带无线，后面考虑加个。我现在没有这个机器

**Comment by bg7pge** [comment]
新固件加了wifi了嘛？官方的功能太少，小白好多不会搞。看上大佬的固件实用，买R5C就是看上小巧的出差方便携带。

**Comment by DHDAXCW** [comment]
木有![image](https://user-images.githubusercontent.com/74764072/214827994-0cb3841e-6c21-4ac5-aef7-5631e29d2409.jpeg)
