### ISSUE TITLE
更改设置无法保存，啥情况？

### ISSUE THREAD

**Issue by Ryan-yl** [DHDAXCW/NanoPi-R5S-R5C#23]
线刷2023.01.17的ext4的稳定版slim-friendlyarm_nanopi-r5s-ext4-sysupgrade.img.gz
登录后台啥也没做就有3条未保存的设置
更改一些设置后点保存或保存并应用，都无法保存设置，重启后恢复到刷机完成是的配置
啥原因呢？

配置 / 修改数 页面显示
smartdns.cfg016bb1
smartdns.cfg016bb1.old_auto_set_dnsmasq=1
smartdns.cfg016bb1.old_enabled=0
smartdns.cfg016bb1.old_port=53

**Comment by DHDAXCW** [comment]
有这样问题，你换sq格式吧

**Comment by DHDAXCW** [comment]
已修复，等今天版本

**Comment by Ryan-yl** [comment]
> 已修复，等今天版本

👍
