### ISSUE TITLE
English Language support

### ISSUE THREAD

**Issue by niklasden** [DHDAXCW/NanoPi-R5S-R5C#24]
Hi there, 

do you have any plans to translate some of the stuff to english?

Will be trying out your image for the r5c soon. 
Thanks for providing all the resources.

Best regards,
Niklas

**Comment by DHDAXCW** [comment]
Firmware follows system settings in English.
![image](https://user-images.githubusercontent.com/74764072/215297719-aadd5e46-befb-4ae4-b2e1-21b45b3e5678.png)
