### ISSUE TITLE
r5c无法正常启动固件

### ISSUE THREAD

**Issue by cjhz2019** [DHDAXCW/NanoPi-R5S-R5C#30]
烧写完固件后上电无法从tf卡启动系统，反而从emmc启动frindlywrt系统

**Comment by DHDAXCW** [comment]
不要有两个系统，不要用引导什么系统，建议要一个系统启动一个盘，想tf启动，就擦掉emmc，想emmc启动，就不要用tf，这友善说引导引导啥的都不要听，开源u-boot和友善用瑞芯微的u-boot不一样，瑞芯微早脱离u-boot主线
