### ISSUE TITLE
2023.02.06 NanoPi-R5S-R5C-linux.6.1版本FULL固件中没有N2N

### ISSUE THREAD

**Issue by jazzly** [DHDAXCW/NanoPi-R5S-R5C#31]
2023.02.06 NanoPi-R5S-R5C-linux.6.1版本FULL固件中没有N2N，ssh进入后台也找不到edge程序。
这个是准备删除了吗？ 可以重新添加吗？

**Comment by DHDAXCW** [comment]
前面版本有？

**Comment by jazzly** [comment]
我是x86那边转过来的，以为插件个数和x86同配置。原来full版本里就没有吗？
我看了一下工作流里面的配置脚本。好像docker版本里有配置。我先去试试。
