### ISSUE TITLE
2023.02.14 NanoPi-R5S-R5C docker 版本无法安装alist

### ISSUE THREAD

**Issue by Sean-Wang** [DHDAXCW/NanoPi-R5S-R5C#39]
NanoPi R5C 使用 docker-friendlyarm_nanopi-r5c-ext4-sysupgrade.img.gz
运行 docker run -d --restart=always -v /etc/alist:/opt/alist/data -p 5244:5244 -e PUID=0 -e PGID=0 -e UMASK=022 --name="alist" xhofe/alist:latest 报错
![image](https://user-images.githubusercontent.com/1193073/219703722-4777c70f-fcbe-4dda-80c8-70f1ce47d72a.png)

请问是什么原因？

**Comment by gngpp** [comment]
> NanoPi R5C 使用 docker-friendlyarm_nanopi-r5c-ext4-sysupgrade.img.gz 运行 docker run -d --restart=always -v /etc/alist:/opt/alist/data -p 5244:5244 -e PUID=0 -e PGID=0 -e UMASK=022 --name="alist" xhofe/alist:latest 报错 ![image](https://user-images.githubusercontent.com/1193073/219703722-4777c70f-fcbe-4dda-80c8-70f1ce47d72a.png)
> 
> 请问是什么原因？

网络有问题

**Comment by Sean-Wang** [comment]
> > NanoPi R5C 使用 docker-friendlyarm_nanopi-r5c-ext4-sysupgrade.img.gz 运行 docker run -d --restart=always -v /etc/alist:/opt/alist/data -p 5244:5244 -e PUID=0 -e PGID=0 -e UMASK=022 --name="alist" xhofe/alist:latest 报错 ![image](https://user-images.githubusercontent.com/1193073/219703722-4777c70f-fcbe-4dda-80c8-70f1ce47d72a.png)
> > 请问是什么原因？
> 
> 网络有问题

网络问题，已接近，谢谢。
