### ISSUE TITLE
电脑网线连接R5C获取不到IP

### ISSUE THREAD

**Issue by bearcolin** [DHDAXCW/NanoPi-R5S-R5C#41]
如题

full-friendlyarm_nanopi-r5c-squashfs-sysupgrade.img.gz
slim-friendlyarm_nanopi-r5c-squashfs-sysupgrade.img.gz
这两个固件

做过如下尝试：
1. 使用mac版etcher烧录到tf卡，插卡启动软路由
2. 使用其他版本固件启动软路由，进入系统后，在后台通过固件升级升级这两个固件
3. 分别试过连接软路由的WAN口和LAN口
4. 分别试过插着mt7921k网卡启动以及拔掉网卡启动

都是一样的表现，电脑一直无法获取到192.168开头的IP

**Comment by DHDAXCW** [comment]
擦掉emmc再启动tf
