### ISSUE TITLE
R5S NVME SSD似乎没法正常加载并且ETH1网口也会出现异常

### ISSUE THREAD

**Issue by BeatCz** [DHDAXCW/NanoPi-R5S-R5C#48]
你好，我R5S硬件，使用
<html>
<body>

固件版本 | OpenWrt Rockchip (2023-02-24) / LuCI Master (git-23.048.51027-d67627a)
-- | --
内核版本 | 6.1.12

</body>
</html>

之前工作一直正常，ETH2接路由器、ETH1接appleTV，最近拓展了一个2TB PCIe4.0的SSD，装上去无法识别，
lspci -k 结果如下
`0000:00:00.0 PCI bridge [0604]: Rockchip Electronics Co., Ltd RK3568 Remote Signal Processor [1d87:3566] (rev 01)
        Kernel driver in use: pcieport
lspci: Unable to load libkmod resources: error -12
0000:01:00.0 Ethernet controller [0200]: Realtek Semiconductor Co., Ltd. RTL8125 2.5GbE Controller [10ec:8125] (rev 05)
        Subsystem: Realtek Semiconductor Co., Ltd. RTL8125 2.5GbE Controller [10ec:8125]
        Kernel driver in use: r8125
0001:10:00.0 PCI bridge [0604]: Rockchip Electronics Co., Ltd RK3568 Remote Signal Processor [1d87:3566] (rev 01)
        Kernel driver in use: pcieport
0001:11:00.0 Ethernet controller [0200]: Realtek Semiconductor Co., Ltd. RTL8125 2.5GbE Controller [10ec:8125] (rev 05)
        Subsystem: Realtek Semiconductor Co., Ltd. RTL8125 2.5GbE Controller [10ec:8125]
        Kernel driver in use: r8125
0002:20:00.0 PCI bridge [0604]: Rockchip Electronics Co., Ltd RK3568 Remote Signal Processor [1d87:3566] (rev 01)
        Kernel driver in use: pcieport
`

且ETH1似乎也不工作了，无论自动IP还是手动均无法正常桥接联网。
不知道是不是NVME驱动需要启动？

**Comment by DHDAXCW** [comment]
刷最新的，那个时候nvme是有问题的

**Comment by BeatCz** [comment]
web更新了最新的版本，已经识别到了，谢谢！
