### ISSUE TITLE
LED 显示错误

### ISSUE THREAD

**Issue by beautifulstars** [DHDAXCW/NanoPi-R5S-R5C#60]
LAN 口通信WAN 口亮，WAN口通信LAN口亮！

**Comment by DHDAXCW** [comment]
你这说的是啥？？

**Comment by Oklasu** [comment]
两个口你只插一个就能上网了？什么锤子问题

**Comment by SiuPual** [comment]
23333

**Comment by beautifulstars** [comment]
@Oklasu  光猫设置为桥接，在只连一个R5C LAN口到光猫的情况下，有LED 闪烁，但是闪烁的是WAN 口的LED ！

**Comment by beautifulstars** [comment]
我试过友善的friendlywrt ，在上述只连R5C 的LAN 口到光猫的情况下，闪烁的是 LAN 的 LED ！

**Comment by DHDAXCW** [comment]
好的，等会我检查看看

**Comment by DHDAXCW** [comment]
我试了其他设备没有问题

**Comment by beautifulstars** [comment]
那我晚上回去用R5C再确认一下！

**Comment by beautifulstars** [comment]
我刚才确认了下，内核版本是  OpenWrt Rockchip (2023-07-01) / LuCI Master (git-23.167.58115-0178b33)  ，确实是有线接LAN口，WAN的LED闪，是对面的LED ，和sys指示灯一起的那个！

**Comment by DHDAXCW** [comment]
也没这问题，你去找卖家换个机器吧
